# Generated by Django 5.0.6 on 2024-07-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='email',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='name',
        ),
    ]
