# Generated by Django 5.0.6 on 2024-07-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogger_email_remove_blogger_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='no_of_blogs',
            field=models.IntegerField(default=0),
        ),
    ]
