# Generated by Django 5.0.6 on 2024-07-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_no_of_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='no_of_blogs',
        ),
        migrations.AddField(
            model_name='blogger',
            name='no_of_blogs',
            field=models.IntegerField(default=0),
        ),
    ]
