# Generated by Django 5.0.6 on 2024-07-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_no_of_blogs_blogger_no_of_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='no_of_blogs',
        ),
    ]
